{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: Beautifulsoup4 in c:\\users\\shubh\\anaconda3\\lib\\site-packages (4.7.1)\n",
      "Requirement already satisfied: soupsieve>=1.2 in c:\\users\\shubh\\anaconda3\\lib\\site-packages (from Beautifulsoup4) (1.8)\n",
      "Note: you may need to restart the kernel to use updated packages.\n"
     ]
    }
   ],
   "source": [
    "pip install Beautifulsoup4\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "5\n",
      "Bad quality\n",
      "Google Chromecast 3 Media Streaming Device  (Black)\n",
      "₹3,499\n",
      "4.5\n",
      "user name Flipkart Customer\n",
      "user rating 5\n",
      "user review Bad quality\n",
      "Google Chromecast 3 Media Streaming Device  (Black),Rs.3499,4.5,Flipkart Customer,5,Bad quality\n",
      "\n",
      "user name Shantanu Chandankhede\n",
      "user rating 5\n",
      "user review Fabulous!\n",
      "Google Chromecast 3 Media Streaming Device  (Black),Rs.3499,4.5,Shantanu Chandankhede,5,Fabulous!\n",
      "\n",
      "user name Vineet Biju\n",
      "user rating 5\n",
      "user review Just wow!\n",
      "Google Chromecast 3 Media Streaming Device  (Black),Rs.3499,4.5,Vineet Biju,5,Just wow!\n",
      "\n",
      "user name ram bhagat  soni\n",
      "user rating 5\n",
      "user review Mind-blowing purchase\n",
      "Google Chromecast 3 Media Streaming Device  (Black),Rs.3499,4.5,ram bhagat  soni,5,Mind-blowing purchase\n",
      "\n",
      "user name Rajeev Dugroch\n",
      "user rating 5\n",
      "user review Perfect product!\n",
      "Google Chromecast 3 Media Streaming Device  (Black),Rs.3499,4.5,Rajeev Dugroch,5,Perfect product!\n",
      "\n",
      "user name Geetanjali Kapoor\n",
      "user rating 3\n",
      "user review Classy product\n",
      "Google Chromecast 3 Media Streaming Device  (Black),Rs.3499,4.5,Geetanjali Kapoor,3,Classy product\n",
      "\n",
      "user name Parmpal  Kaur\n",
      "user rating 4\n",
      "user review Just okay\n",
      "Google Chromecast 3 Media Streaming Device  (Black),Rs.3499,4.5,Parmpal  Kaur,4,Just okay\n",
      "\n",
      "user name Yuvan Sridhar\n",
      "user rating 5\n",
      "user review Good quality product\n",
      "Google Chromecast 3 Media Streaming Device  (Black),Rs.3499,4.5,Yuvan Sridhar,5,Good quality product\n",
      "\n",
      "user name pritam ghosh\n",
      "user rating 5\n",
      "user review Wonderful\n",
      "Google Chromecast 3 Media Streaming Device  (Black),Rs.3499,4.5,pritam ghosh,5,Wonderful\n",
      "\n"
     ]
    }
   ],
   "source": [
    "\n",
    "from urllib.request import urlopen as uReq\n",
    "\n",
    "from bs4 import BeautifulSoup as soup\n",
    "\n",
    "my_url=\"https://www.flipkart.com/google-chromecast-3-media-streaming-device/p/itmf9fc9hggsyzs5\"\n",
    "\n",
    "\n",
    "uClient = uReq(my_url)\n",
    "page_html = uClient.read()\n",
    "uClient.close()\n",
    "page_soup = soup(page_html, \"html.parser\")\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "containers = page_soup.findAll(\"div\", { \"class\": \"_1HmYoV _35HD7C col-8-12\"})\n",
    "#print(len(containers))\n",
    "\n",
    "#print(soup.prettify(containers[0]))\n",
    "\n",
    "container = containers[0]\n",
    "#print(container.div.img[\"alt\"])\n",
    "\n",
    "\n",
    "SingleUserRating = container.findAll(\"div\", {\"class\": \"hGSR34 E_uFuv\"})\n",
    "\n",
    "\n",
    "print(SingleUserRating[0].text)\n",
    "\n",
    "SingleUserReview = container.findAll(\"p\", {\"class\": \"_2xg6Ul\"})\n",
    "\n",
    "print(SingleUserReview[0].text)\n",
    "\n",
    "SingleUserName = container.findAll(\"p\", {\"class\": \"_3LYOAd _3sxSiS\"})\n",
    "\n",
    "product_name = container.findAll(\"span\", {\"class\": \"_35KyD6\"})\n",
    "print(product_name[0].text)\n",
    "product_name = product_name[0].text\n",
    "\n",
    "product_price = container.findAll(\"div\", {\"class\": \"_1vC4OE _3qQ9m1\"})\n",
    "print(product_price[0].text)\n",
    "price = product_price[0].text\n",
    "\n",
    "trim_price = ''.join(price.split(','))\n",
    "rm_rupee = trim_price.split('₹')\n",
    "add_rs_price = \"Rs.\" + rm_rupee[1]\n",
    "split_price = add_rs_price.split('E')\n",
    "product_price = split_price[0]\n",
    "\n",
    "product_rating = container.findAll(\"div\", {\"class\": \"hGSR34\"})\n",
    "print(product_rating[0].text)\n",
    "product_rating = product_rating[0].text\n",
    "\"\"\"\n",
    "\n",
    "ratings = container.findAll(\"div\", {\"class\": \"niH0FQ\"})\n",
    "#rint(ratings[0].text)\n",
    "\"\"\"\n",
    "filename = \"products.csv\"\n",
    "import io\n",
    "f = io.open(filename, \"a\", encoding=\"utf-8\")\n",
    "\n",
    "#headers = \"Product_Name, Pricing, Ratings, User_Name, User_Rating, User_Review \\n\"\n",
    "#f.write(headers)\n",
    "\n",
    "for i in range(0, len(SingleUserRating)):\n",
    "\n",
    "    uname = SingleUserName[i].text\n",
    "    urating = SingleUserRating[i].text\n",
    "    ureview = SingleUserReview[i].text\n",
    "    print(\"user name \" + uname)\n",
    "    print(\"user rating \"+ urating)\n",
    "    print(\"user review \" + ureview)\n",
    "    print(product_name + \",\" + product_price + \",\" + product_rating  + \",\" + uname  + \",\" + urating  + \",\" + ureview  + \"\\n\")\n",
    "    f.write(product_name + \",\" + product_price + \",\" + product_rating  + \",\" + uname  + \",\" + urating  + \",\" + ureview  + \"\\n\")\n",
    "f.close()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
